version: '3'
services:
  flask:
    build: ./
    container_name: sns-backend               
    restart: on-failure
    volumes:
      - ./:/backend
    ports:
      - "8000:8000"
    command: python app.py